config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index', as: 'home'
  get '/notes' => 'notes#index'
  post '/create_note' => 'notes#create'
  get 'search', to: 'searches#search'
  # Showing user login, logging them in, logging them out
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  patch '/password' => 'password#update'
  get '/password' => 'password#edit'
  get '/note_roadblocks/:id' => 'solutions#show'

  resources :notes do
    resources :comments
  end

  resources :note_roadblocks do
    resources :solutions
  end

  resources :teams
  resources :password
  resources :admin do
    member do
      patch :set_admin
      delete :remove_admin
    end
  end
  resources :employees
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  has_many :notes
  default_scope { order(:last_name, :first_name) }
  has_and_belongs_to_many :team

  def self.active
    Employee.where.not(users_id: nil).to_a
  end

  def teams
    team_ids = EmployeesTeam.where(employees_id: id, active: true).map(&:teams_id).uniq
    Team.find(team_ids)
  end

  def roadblock_for(note_id)
    NoteRoadblock.where(employees_id: id, note_id: note_id)
  end

  def first_name=(val)
    write_attribute(:first_name, val.strip.capitalize)
  end

  def last_name=(val)
    write_attribute(:last_name, val.strip.capitalize)
  end

  def email_address=(val)
    write_attribute(:email_address, val.strip.downcase)
  end

  def as_user
    User.find_by(id: users_id)
  end

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :authorize
  before_action :authorize_access_to_employee_info

  def show
    redirect_to home_path unless current_user.admin? || params[:id].to_i == current_user.as_employee&.id
    @employee = Employee.find(params[:id])
    @teams = @employee.teams
    @user = @employee.as_user

    note_bodies = NoteBody.where(employees_id: params[:id]).map(&:note_id)
    note_roadblocks = NoteRoadblock.where(employees_id: params[:id]).map(&:note_id)
    all_notes = note_bodies | note_roadblocks

    all_notes_for_employee = Note.find(all_notes.compact)

    @employee_notes = []
    all_notes_for_employee&.each do |note|
      @employee_notes << {
        date: note.created_at,
        id: note.id,
        title: note.title,
        body: note.body_for(@employee.id),
        roadblocks: note.roadblock_for(@employee.id)
      }
    end

    @records = []

    EmployeesTeam.where(employees_id: @employee.id).each do |record|
      @records << "Added to #{Team.find(record.teams_id).name} on #{record.created_at.in_time_zone('America/Chicago').strftime('%b %d, %Y')}" # rubocop:disable Metrics/LineLength
      unless record.active?
        @records << "Removed from #{Team.find(record.teams_id).name}  on #{record.updated_at.in_time_zone('America/Chicago').strftime('%b %d, %Y')}" # rubocop:disable Metrics/LineLength
      end
    end
  end

  def destroy
    employee = Employee.find(params[:id])
    user = employee.as_user

    if Team.leads.include?(employee)
      redirect_to admin_index_path, danger: "Unable to remove #{employee.first_name} while still a pod lead. Please remove from role and try again." # rubocop:disable Metrics/LineLength
    else
      is_success = ActiveRecord::Base.transaction do
        raise ActiveRecord::Rollback unless EmployeesTeam.where(employees_id: employee.id).update_all(active: false)
        raise ActiveRecord::Rollback unless UserRole.where(users_id: user.id).destroy_all

        employee.update!(users_id: nil)
        user.destroy!
      end
      if is_success
        redirect_to admin_index_path, success: 'Employee deleted'
      else
        redirect_to admin_index_path, danger: 'Unable to remove employee'
      end
    end
  end

  def authorize_access_to_employee_info
    redirect_to home_path unless current_user.admin? || params[:id].to_i == current_user.as_employee&.id
  end
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

module EmployeesHelper
end

app/views/employees/show.html.erb
<div class="notes-wrapper">
	<div class="team-card">
		<h6>Employee Name</h6>
	 	<h1><%= @employee.first_name %> <%= @employee.last_name %></h1>
	</div>

	<div class="team-card">
		<h6>Current Pods</h6>
		<% if @teams.blank? %>
			<h3><i>Not assigned to any pods yet</i></h3>
		<% else %>
      <ul>
        <% @teams.each do |team| %>
          <li><%= link_to "#{team.name}", team_path(team.id) %></li>
        <% end %>
      </ul>
		<% end %>
	</div>

	<div class="team-card">
		<h6>Pod History</h6>
		<ul>
			<% @records.each do |record|%>
				<li><%= record %></li>
			<% end %>
		</ul>
	</div>

	<div class="team-card" style="width:80%;">
		<h6>Note History</h6>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Note</th>
          <th>Roadblocks</th>
          <th style="width:150px;">Date</th>
          <th class="text-center" style="width:100px;">Action</th>
        </tr>
      </thead>
      <% @employee_notes.each do |note| %>
        <tr class="custab">
          <td><%= note[:body] %></td>
          <td><%= note[:roadblocks] %></td>
          <td><%= note[:date].in_time_zone('America/Chicago').strftime('%a %D') %></td>
          <td class="text-center">
            <%= link_to "View", note_path(note[:id]), class: 'btn btn-info btn-xs' %>
          </td>
        </tr>
      <%end%>
    </table>
  </div>
</div>
<br>